-- Create chat_history table
CREATE TABLE chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    message TEXT NOT NULL,
    sender VARCHAR(10) NOT NULL CHECK (sender IN ('user', 'bot')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to read their own chat history
CREATE POLICY "Users can read their own chat history" ON chat_history
    FOR SELECT
    USING (auth.uid() = user_id);

-- Create policy to allow users to insert their own chat history
CREATE POLICY "Users can insert their own chat history" ON chat_history
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);
