-- Create chat_history table
CREATE TABLE chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    message TEXT NOT NULL,
    sender VARCHAR(10) NOT NULL CHECK (sender IN ('user', 'bot')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to read their own chat history
CREATE POLICY "Users can read their own chat history" ON chat_history
    FOR SELECT
    USING (auth.uid() = user_id);

-- Create policy to allow users to insert their own chat history
CREATE POLICY "Users can insert their own chat history" ON chat_history
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Create mood_history table
CREATE TABLE mood_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    mood VARCHAR(20) NOT NULL,
    confidence INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE mood_history ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to read their own mood history
CREATE POLICY "Users can read their own mood history" ON mood_history
    FOR SELECT
    USING (auth.uid() = user_id);

-- Create policy to allow users to insert their own mood history
CREATE POLICY "Users can insert their own mood history" ON mood_history
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Create membership table
CREATE TABLE memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    plan VARCHAR(20) NOT NULL DEFAULT 'free', -- 'free' or 'premium'
    starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ends_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to read their own membership
CREATE POLICY "Users can read their own membership" ON memberships
    FOR SELECT
    USING (auth.uid() = user_id);

-- Create policy to allow users to insert their own membership
CREATE POLICY "Users can insert their own membership" ON memberships
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);
