/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoEdukasiRouteRouteImport } from './routes/video-edukasi/route'
import { Route as TwinRouteRouteImport } from './routes/twin/route'
import { Route as TipsSehatRouteRouteImport } from './routes/tips-sehat/route'
import { Route as SymptomTriageRouteRouteImport } from './routes/symptom-triage/route'
import { Route as ResepRouteRouteImport } from './routes/resep/route'
import { Route as RekamMedisRouteRouteImport } from './routes/rekam-medis/route'
import { Route as ProfilRouteRouteImport } from './routes/profil/route'
import { Route as MoodCheckRouteRouteImport } from './routes/mood-check/route'
import { Route as MentalHealthRouteRouteImport } from './routes/mental-health/route'
import { Route as MarketplaceRouteRouteImport } from './routes/marketplace/route'
import { Route as KonsulRouteRouteImport } from './routes/konsul/route'
import { Route as KomunitasPasienRouteRouteImport } from './routes/komunitas-pasien/route'
import { Route as DokterRouteRouteImport } from './routes/dokter/route'
import { Route as DermatologiRouteRouteImport } from './routes/dermatologi/route'
import { Route as CekJantungRouteRouteImport } from './routes/cek-jantung/route'
import { Route as BerandaRouteRouteImport } from './routes/beranda/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ArtikelRouteRouteImport } from './routes/artikel/route'
import { Route as IndexRouteImport } from './routes/index'

const VideoEdukasiRouteRoute = VideoEdukasiRouteRouteImport.update({
  id: '/video-edukasi',
  path: '/video-edukasi',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRouteRoute = TwinRouteRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsSehatRouteRoute = TipsSehatRouteRouteImport.update({
  id: '/tips-sehat',
  path: '/tips-sehat',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomTriageRouteRoute = SymptomTriageRouteRouteImport.update({
  id: '/symptom-triage',
  path: '/symptom-triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ResepRouteRoute = ResepRouteRouteImport.update({
  id: '/resep',
  path: '/resep',
  getParentRoute: () => rootRouteImport,
} as any)
const RekamMedisRouteRoute = RekamMedisRouteRouteImport.update({
  id: '/rekam-medis',
  path: '/rekam-medis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRouteRoute = ProfilRouteRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodCheckRouteRoute = MoodCheckRouteRouteImport.update({
  id: '/mood-check',
  path: '/mood-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalHealthRouteRoute = MentalHealthRouteRouteImport.update({
  id: '/mental-health',
  path: '/mental-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRouteRoute = MarketplaceRouteRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsulRouteRoute = KonsulRouteRouteImport.update({
  id: '/konsul',
  path: '/konsul',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunitasPasienRouteRoute = KomunitasPasienRouteRouteImport.update({
  id: '/komunitas-pasien',
  path: '/komunitas-pasien',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterRouteRoute = DokterRouteRouteImport.update({
  id: '/dokter',
  path: '/dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const DermatologiRouteRoute = DermatologiRouteRouteImport.update({
  id: '/dermatologi',
  path: '/dermatologi',
  getParentRoute: () => rootRouteImport,
} as any)
const CekJantungRouteRoute = CekJantungRouteRouteImport.update({
  id: '/cek-jantung',
  path: '/cek-jantung',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRouteRoute = BerandaRouteRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRouteRoute = ArtikelRouteRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteRoute
  '/auth': typeof AuthRouteRoute
  '/beranda': typeof BerandaRouteRoute
  '/cek-jantung': typeof CekJantungRouteRoute
  '/dermatologi': typeof DermatologiRouteRoute
  '/dokter': typeof DokterRouteRoute
  '/komunitas-pasien': typeof KomunitasPasienRouteRoute
  '/konsul': typeof KonsulRouteRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/mental-health': typeof MentalHealthRouteRoute
  '/mood-check': typeof MoodCheckRouteRoute
  '/profil': typeof ProfilRouteRoute
  '/rekam-medis': typeof RekamMedisRouteRoute
  '/resep': typeof ResepRouteRoute
  '/symptom-triage': typeof SymptomTriageRouteRoute
  '/tips-sehat': typeof TipsSehatRouteRoute
  '/twin': typeof TwinRouteRoute
  '/video-edukasi': typeof VideoEdukasiRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteRoute
  '/auth': typeof AuthRouteRoute
  '/beranda': typeof BerandaRouteRoute
  '/cek-jantung': typeof CekJantungRouteRoute
  '/dermatologi': typeof DermatologiRouteRoute
  '/dokter': typeof DokterRouteRoute
  '/komunitas-pasien': typeof KomunitasPasienRouteRoute
  '/konsul': typeof KonsulRouteRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/mental-health': typeof MentalHealthRouteRoute
  '/mood-check': typeof MoodCheckRouteRoute
  '/profil': typeof ProfilRouteRoute
  '/rekam-medis': typeof RekamMedisRouteRoute
  '/resep': typeof ResepRouteRoute
  '/symptom-triage': typeof SymptomTriageRouteRoute
  '/tips-sehat': typeof TipsSehatRouteRoute
  '/twin': typeof TwinRouteRoute
  '/video-edukasi': typeof VideoEdukasiRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteRoute
  '/auth': typeof AuthRouteRoute
  '/beranda': typeof BerandaRouteRoute
  '/cek-jantung': typeof CekJantungRouteRoute
  '/dermatologi': typeof DermatologiRouteRoute
  '/dokter': typeof DokterRouteRoute
  '/komunitas-pasien': typeof KomunitasPasienRouteRoute
  '/konsul': typeof KonsulRouteRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/mental-health': typeof MentalHealthRouteRoute
  '/mood-check': typeof MoodCheckRouteRoute
  '/profil': typeof ProfilRouteRoute
  '/rekam-medis': typeof RekamMedisRouteRoute
  '/resep': typeof ResepRouteRoute
  '/symptom-triage': typeof SymptomTriageRouteRoute
  '/tips-sehat': typeof TipsSehatRouteRoute
  '/twin': typeof TwinRouteRoute
  '/video-edukasi': typeof VideoEdukasiRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/auth'
    | '/beranda'
    | '/cek-jantung'
    | '/dermatologi'
    | '/dokter'
    | '/komunitas-pasien'
    | '/konsul'
    | '/marketplace'
    | '/mental-health'
    | '/mood-check'
    | '/profil'
    | '/rekam-medis'
    | '/resep'
    | '/symptom-triage'
    | '/tips-sehat'
    | '/twin'
    | '/video-edukasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/auth'
    | '/beranda'
    | '/cek-jantung'
    | '/dermatologi'
    | '/dokter'
    | '/komunitas-pasien'
    | '/konsul'
    | '/marketplace'
    | '/mental-health'
    | '/mood-check'
    | '/profil'
    | '/rekam-medis'
    | '/resep'
    | '/symptom-triage'
    | '/tips-sehat'
    | '/twin'
    | '/video-edukasi'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/auth'
    | '/beranda'
    | '/cek-jantung'
    | '/dermatologi'
    | '/dokter'
    | '/komunitas-pasien'
    | '/konsul'
    | '/marketplace'
    | '/mental-health'
    | '/mood-check'
    | '/profil'
    | '/rekam-medis'
    | '/resep'
    | '/symptom-triage'
    | '/tips-sehat'
    | '/twin'
    | '/video-edukasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRouteRoute: typeof ArtikelRouteRoute
  AuthRouteRoute: typeof AuthRouteRoute
  BerandaRouteRoute: typeof BerandaRouteRoute
  CekJantungRouteRoute: typeof CekJantungRouteRoute
  DermatologiRouteRoute: typeof DermatologiRouteRoute
  DokterRouteRoute: typeof DokterRouteRoute
  KomunitasPasienRouteRoute: typeof KomunitasPasienRouteRoute
  KonsulRouteRoute: typeof KonsulRouteRoute
  MarketplaceRouteRoute: typeof MarketplaceRouteRoute
  MentalHealthRouteRoute: typeof MentalHealthRouteRoute
  MoodCheckRouteRoute: typeof MoodCheckRouteRoute
  ProfilRouteRoute: typeof ProfilRouteRoute
  RekamMedisRouteRoute: typeof RekamMedisRouteRoute
  ResepRouteRoute: typeof ResepRouteRoute
  SymptomTriageRouteRoute: typeof SymptomTriageRouteRoute
  TipsSehatRouteRoute: typeof TipsSehatRouteRoute
  TwinRouteRoute: typeof TwinRouteRoute
  VideoEdukasiRouteRoute: typeof VideoEdukasiRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-edukasi': {
      id: '/video-edukasi'
      path: '/video-edukasi'
      fullPath: '/video-edukasi'
      preLoaderRoute: typeof VideoEdukasiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips-sehat': {
      id: '/tips-sehat'
      path: '/tips-sehat'
      fullPath: '/tips-sehat'
      preLoaderRoute: typeof TipsSehatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-triage': {
      id: '/symptom-triage'
      path: '/symptom-triage'
      fullPath: '/symptom-triage'
      preLoaderRoute: typeof SymptomTriageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resep': {
      id: '/resep'
      path: '/resep'
      fullPath: '/resep'
      preLoaderRoute: typeof ResepRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekam-medis': {
      id: '/rekam-medis'
      path: '/rekam-medis'
      fullPath: '/rekam-medis'
      preLoaderRoute: typeof RekamMedisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-check': {
      id: '/mood-check'
      path: '/mood-check'
      fullPath: '/mood-check'
      preLoaderRoute: typeof MoodCheckRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-health': {
      id: '/mental-health'
      path: '/mental-health'
      fullPath: '/mental-health'
      preLoaderRoute: typeof MentalHealthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsul': {
      id: '/konsul'
      path: '/konsul'
      fullPath: '/konsul'
      preLoaderRoute: typeof KonsulRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunitas-pasien': {
      id: '/komunitas-pasien'
      path: '/komunitas-pasien'
      fullPath: '/komunitas-pasien'
      preLoaderRoute: typeof KomunitasPasienRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter': {
      id: '/dokter'
      path: '/dokter'
      fullPath: '/dokter'
      preLoaderRoute: typeof DokterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dermatologi': {
      id: '/dermatologi'
      path: '/dermatologi'
      fullPath: '/dermatologi'
      preLoaderRoute: typeof DermatologiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-jantung': {
      id: '/cek-jantung'
      path: '/cek-jantung'
      fullPath: '/cek-jantung'
      preLoaderRoute: typeof CekJantungRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRouteRoute: ArtikelRouteRoute,
  AuthRouteRoute: AuthRouteRoute,
  BerandaRouteRoute: BerandaRouteRoute,
  CekJantungRouteRoute: CekJantungRouteRoute,
  DermatologiRouteRoute: DermatologiRouteRoute,
  DokterRouteRoute: DokterRouteRoute,
  KomunitasPasienRouteRoute: KomunitasPasienRouteRoute,
  KonsulRouteRoute: KonsulRouteRoute,
  MarketplaceRouteRoute: MarketplaceRouteRoute,
  MentalHealthRouteRoute: MentalHealthRouteRoute,
  MoodCheckRouteRoute: MoodCheckRouteRoute,
  ProfilRouteRoute: ProfilRouteRoute,
  RekamMedisRouteRoute: RekamMedisRouteRoute,
  ResepRouteRoute: ResepRouteRoute,
  SymptomTriageRouteRoute: SymptomTriageRouteRoute,
  TipsSehatRouteRoute: TipsSehatRouteRoute,
  TwinRouteRoute: TwinRouteRoute,
  VideoEdukasiRouteRoute: VideoEdukasiRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
