/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoEdukasiRouteRouteImport } from './routes/video-edukasi/route'
import { Route as TwinRouteRouteImport } from './routes/twin/route'
import { Route as SymptomTriageRouteRouteImport } from './routes/symptom-triage/route'
import { Route as ResepRouteRouteImport } from './routes/resep/route'
import { Route as RekamMedisRouteRouteImport } from './routes/rekam-medis/route'
import { Route as ProfilRouteRouteImport } from './routes/profil/route'
import { Route as PaymentRouteRouteImport } from './routes/payment/route'
import { Route as MoodCheckRouteRouteImport } from './routes/mood-check/route'
import { Route as MentalHealthRouteRouteImport } from './routes/mental-health/route'
import { Route as MembershipRouteRouteImport } from './routes/membership/route'
import { Route as MarketplaceRouteRouteImport } from './routes/marketplace/route'
import { Route as MaintenanceRouteRouteImport } from './routes/maintenance/route'
import { Route as KonsulRouteRouteImport } from './routes/konsul/route'
import { Route as KomunitasPasienRouteRouteImport } from './routes/komunitas-pasien/route'
import { Route as DokterRouteRouteImport } from './routes/dokter/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as DermatologiRouteRouteImport } from './routes/dermatologi/route'
import { Route as DaftarDokterRouteRouteImport } from './routes/daftar-dokter/route'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as CekJantungRouteRouteImport } from './routes/cek-jantung/route'
import { Route as BookingRouteRouteImport } from './routes/booking/route'
import { Route as BerandaRouteRouteImport } from './routes/beranda/route'
import { Route as BannedRouteRouteImport } from './routes/banned/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ArtikelRouteRouteImport } from './routes/artikel/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as DoctorSettingsRouteRouteImport } from './routes/doctor/settings/route'
import { Route as DoctorPrescriptionsRouteRouteImport } from './routes/doctor/prescriptions/route'
import { Route as DoctorPatientsRouteRouteImport } from './routes/doctor/patients/route'
import { Route as DoctorConsultationsRouteRouteImport } from './routes/doctor/consultations/route'
import { Route as DoctorChatRouteRouteImport } from './routes/doctor/chat/route'
import { Route as DoctorAnalyticsRouteRouteImport } from './routes/doctor/analytics/route'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminMarketplaceRouteRouteImport } from './routes/admin/marketplace/route'
import { Route as AdminLiveChatRouteRouteImport } from './routes/admin/live-chat/route'
import { Route as AdminDoctorsRouteRouteImport } from './routes/admin/doctors/route'

const VideoEdukasiRouteRoute = VideoEdukasiRouteRouteImport.update({
  id: '/video-edukasi',
  path: '/video-edukasi',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRouteRoute = TwinRouteRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomTriageRouteRoute = SymptomTriageRouteRouteImport.update({
  id: '/symptom-triage',
  path: '/symptom-triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ResepRouteRoute = ResepRouteRouteImport.update({
  id: '/resep',
  path: '/resep',
  getParentRoute: () => rootRouteImport,
} as any)
const RekamMedisRouteRoute = RekamMedisRouteRouteImport.update({
  id: '/rekam-medis',
  path: '/rekam-medis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRouteRoute = ProfilRouteRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRouteRoute = PaymentRouteRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodCheckRouteRoute = MoodCheckRouteRouteImport.update({
  id: '/mood-check',
  path: '/mood-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalHealthRouteRoute = MentalHealthRouteRouteImport.update({
  id: '/mental-health',
  path: '/mental-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRouteRoute = MembershipRouteRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRouteRoute = MarketplaceRouteRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRouteRoute = MaintenanceRouteRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsulRouteRoute = KonsulRouteRouteImport.update({
  id: '/konsul',
  path: '/konsul',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunitasPasienRouteRoute = KomunitasPasienRouteRouteImport.update({
  id: '/komunitas-pasien',
  path: '/komunitas-pasien',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterRouteRoute = DokterRouteRouteImport.update({
  id: '/dokter',
  path: '/dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DermatologiRouteRoute = DermatologiRouteRouteImport.update({
  id: '/dermatologi',
  path: '/dermatologi',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarDokterRouteRoute = DaftarDokterRouteRouteImport.update({
  id: '/daftar-dokter',
  path: '/daftar-dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CekJantungRouteRoute = CekJantungRouteRouteImport.update({
  id: '/cek-jantung',
  path: '/cek-jantung',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRouteRoute = BookingRouteRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRouteRoute = BerandaRouteRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRouteRoute = BannedRouteRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRouteRoute = ArtikelRouteRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DoctorSettingsRouteRoute = DoctorSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPrescriptionsRouteRoute =
  DoctorPrescriptionsRouteRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const DoctorPatientsRouteRoute = DoctorPatientsRouteRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorConsultationsRouteRoute =
  DoctorConsultationsRouteRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => DoctorRouteRoute,
  } as any)
const DoctorChatRouteRoute = DoctorChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorAnalyticsRouteRoute = DoctorAnalyticsRouteRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketplaceRouteRoute = AdminMarketplaceRouteRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLiveChatRouteRoute = AdminLiveChatRouteRouteImport.update({
  id: '/live-chat',
  path: '/live-chat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRouteRoute = AdminDoctorsRouteRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/artikel': typeof ArtikelRouteRoute
  '/auth': typeof AuthRouteRoute
  '/banned': typeof BannedRouteRoute
  '/beranda': typeof BerandaRouteRoute
  '/booking': typeof BookingRouteRoute
  '/cek-jantung': typeof CekJantungRouteRoute
  '/chat': typeof ChatRouteRoute
  '/daftar-dokter': typeof DaftarDokterRouteRoute
  '/dermatologi': typeof DermatologiRouteRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/dokter': typeof DokterRouteRoute
  '/komunitas-pasien': typeof KomunitasPasienRouteRoute
  '/konsul': typeof KonsulRouteRoute
  '/maintenance': typeof MaintenanceRouteRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/membership': typeof MembershipRouteRoute
  '/mental-health': typeof MentalHealthRouteRoute
  '/mood-check': typeof MoodCheckRouteRoute
  '/payment': typeof PaymentRouteRoute
  '/profil': typeof ProfilRouteRoute
  '/rekam-medis': typeof RekamMedisRouteRoute
  '/resep': typeof ResepRouteRoute
  '/symptom-triage': typeof SymptomTriageRouteRoute
  '/twin': typeof TwinRouteRoute
  '/video-edukasi': typeof VideoEdukasiRouteRoute
  '/admin/doctors': typeof AdminDoctorsRouteRoute
  '/admin/live-chat': typeof AdminLiveChatRouteRoute
  '/admin/marketplace': typeof AdminMarketplaceRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/doctor/analytics': typeof DoctorAnalyticsRouteRoute
  '/doctor/chat': typeof DoctorChatRouteRoute
  '/doctor/consultations': typeof DoctorConsultationsRouteRoute
  '/doctor/patients': typeof DoctorPatientsRouteRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRouteRoute
  '/doctor/settings': typeof DoctorSettingsRouteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteRoute
  '/auth': typeof AuthRouteRoute
  '/banned': typeof BannedRouteRoute
  '/beranda': typeof BerandaRouteRoute
  '/booking': typeof BookingRouteRoute
  '/cek-jantung': typeof CekJantungRouteRoute
  '/chat': typeof ChatRouteRoute
  '/daftar-dokter': typeof DaftarDokterRouteRoute
  '/dermatologi': typeof DermatologiRouteRoute
  '/dokter': typeof DokterRouteRoute
  '/komunitas-pasien': typeof KomunitasPasienRouteRoute
  '/konsul': typeof KonsulRouteRoute
  '/maintenance': typeof MaintenanceRouteRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/membership': typeof MembershipRouteRoute
  '/mental-health': typeof MentalHealthRouteRoute
  '/mood-check': typeof MoodCheckRouteRoute
  '/payment': typeof PaymentRouteRoute
  '/profil': typeof ProfilRouteRoute
  '/rekam-medis': typeof RekamMedisRouteRoute
  '/resep': typeof ResepRouteRoute
  '/symptom-triage': typeof SymptomTriageRouteRoute
  '/twin': typeof TwinRouteRoute
  '/video-edukasi': typeof VideoEdukasiRouteRoute
  '/admin/doctors': typeof AdminDoctorsRouteRoute
  '/admin/live-chat': typeof AdminLiveChatRouteRoute
  '/admin/marketplace': typeof AdminMarketplaceRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/doctor/analytics': typeof DoctorAnalyticsRouteRoute
  '/doctor/chat': typeof DoctorChatRouteRoute
  '/doctor/consultations': typeof DoctorConsultationsRouteRoute
  '/doctor/patients': typeof DoctorPatientsRouteRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRouteRoute
  '/doctor/settings': typeof DoctorSettingsRouteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/artikel': typeof ArtikelRouteRoute
  '/auth': typeof AuthRouteRoute
  '/banned': typeof BannedRouteRoute
  '/beranda': typeof BerandaRouteRoute
  '/booking': typeof BookingRouteRoute
  '/cek-jantung': typeof CekJantungRouteRoute
  '/chat': typeof ChatRouteRoute
  '/daftar-dokter': typeof DaftarDokterRouteRoute
  '/dermatologi': typeof DermatologiRouteRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/dokter': typeof DokterRouteRoute
  '/komunitas-pasien': typeof KomunitasPasienRouteRoute
  '/konsul': typeof KonsulRouteRoute
  '/maintenance': typeof MaintenanceRouteRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/membership': typeof MembershipRouteRoute
  '/mental-health': typeof MentalHealthRouteRoute
  '/mood-check': typeof MoodCheckRouteRoute
  '/payment': typeof PaymentRouteRoute
  '/profil': typeof ProfilRouteRoute
  '/rekam-medis': typeof RekamMedisRouteRoute
  '/resep': typeof ResepRouteRoute
  '/symptom-triage': typeof SymptomTriageRouteRoute
  '/twin': typeof TwinRouteRoute
  '/video-edukasi': typeof VideoEdukasiRouteRoute
  '/admin/doctors': typeof AdminDoctorsRouteRoute
  '/admin/live-chat': typeof AdminLiveChatRouteRoute
  '/admin/marketplace': typeof AdminMarketplaceRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/doctor/analytics': typeof DoctorAnalyticsRouteRoute
  '/doctor/chat': typeof DoctorChatRouteRoute
  '/doctor/consultations': typeof DoctorConsultationsRouteRoute
  '/doctor/patients': typeof DoctorPatientsRouteRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRouteRoute
  '/doctor/settings': typeof DoctorSettingsRouteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artikel'
    | '/auth'
    | '/banned'
    | '/beranda'
    | '/booking'
    | '/cek-jantung'
    | '/chat'
    | '/daftar-dokter'
    | '/dermatologi'
    | '/doctor'
    | '/dokter'
    | '/komunitas-pasien'
    | '/konsul'
    | '/maintenance'
    | '/marketplace'
    | '/membership'
    | '/mental-health'
    | '/mood-check'
    | '/payment'
    | '/profil'
    | '/rekam-medis'
    | '/resep'
    | '/symptom-triage'
    | '/twin'
    | '/video-edukasi'
    | '/admin/doctors'
    | '/admin/live-chat'
    | '/admin/marketplace'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/chat'
    | '/doctor/consultations'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/settings'
    | '/admin/login'
    | '/admin/'
    | '/doctor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/auth'
    | '/banned'
    | '/beranda'
    | '/booking'
    | '/cek-jantung'
    | '/chat'
    | '/daftar-dokter'
    | '/dermatologi'
    | '/dokter'
    | '/komunitas-pasien'
    | '/konsul'
    | '/maintenance'
    | '/marketplace'
    | '/membership'
    | '/mental-health'
    | '/mood-check'
    | '/payment'
    | '/profil'
    | '/rekam-medis'
    | '/resep'
    | '/symptom-triage'
    | '/twin'
    | '/video-edukasi'
    | '/admin/doctors'
    | '/admin/live-chat'
    | '/admin/marketplace'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/chat'
    | '/doctor/consultations'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/settings'
    | '/admin/login'
    | '/admin'
    | '/doctor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artikel'
    | '/auth'
    | '/banned'
    | '/beranda'
    | '/booking'
    | '/cek-jantung'
    | '/chat'
    | '/daftar-dokter'
    | '/dermatologi'
    | '/doctor'
    | '/dokter'
    | '/komunitas-pasien'
    | '/konsul'
    | '/maintenance'
    | '/marketplace'
    | '/membership'
    | '/mental-health'
    | '/mood-check'
    | '/payment'
    | '/profil'
    | '/rekam-medis'
    | '/resep'
    | '/symptom-triage'
    | '/twin'
    | '/video-edukasi'
    | '/admin/doctors'
    | '/admin/live-chat'
    | '/admin/marketplace'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/chat'
    | '/doctor/consultations'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/settings'
    | '/admin/login'
    | '/admin/'
    | '/doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ArtikelRouteRoute: typeof ArtikelRouteRoute
  AuthRouteRoute: typeof AuthRouteRoute
  BannedRouteRoute: typeof BannedRouteRoute
  BerandaRouteRoute: typeof BerandaRouteRoute
  BookingRouteRoute: typeof BookingRouteRoute
  CekJantungRouteRoute: typeof CekJantungRouteRoute
  ChatRouteRoute: typeof ChatRouteRoute
  DaftarDokterRouteRoute: typeof DaftarDokterRouteRoute
  DermatologiRouteRoute: typeof DermatologiRouteRoute
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  DokterRouteRoute: typeof DokterRouteRoute
  KomunitasPasienRouteRoute: typeof KomunitasPasienRouteRoute
  KonsulRouteRoute: typeof KonsulRouteRoute
  MaintenanceRouteRoute: typeof MaintenanceRouteRoute
  MarketplaceRouteRoute: typeof MarketplaceRouteRoute
  MembershipRouteRoute: typeof MembershipRouteRoute
  MentalHealthRouteRoute: typeof MentalHealthRouteRoute
  MoodCheckRouteRoute: typeof MoodCheckRouteRoute
  PaymentRouteRoute: typeof PaymentRouteRoute
  ProfilRouteRoute: typeof ProfilRouteRoute
  RekamMedisRouteRoute: typeof RekamMedisRouteRoute
  ResepRouteRoute: typeof ResepRouteRoute
  SymptomTriageRouteRoute: typeof SymptomTriageRouteRoute
  TwinRouteRoute: typeof TwinRouteRoute
  VideoEdukasiRouteRoute: typeof VideoEdukasiRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-edukasi': {
      id: '/video-edukasi'
      path: '/video-edukasi'
      fullPath: '/video-edukasi'
      preLoaderRoute: typeof VideoEdukasiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-triage': {
      id: '/symptom-triage'
      path: '/symptom-triage'
      fullPath: '/symptom-triage'
      preLoaderRoute: typeof SymptomTriageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resep': {
      id: '/resep'
      path: '/resep'
      fullPath: '/resep'
      preLoaderRoute: typeof ResepRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekam-medis': {
      id: '/rekam-medis'
      path: '/rekam-medis'
      fullPath: '/rekam-medis'
      preLoaderRoute: typeof RekamMedisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-check': {
      id: '/mood-check'
      path: '/mood-check'
      fullPath: '/mood-check'
      preLoaderRoute: typeof MoodCheckRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-health': {
      id: '/mental-health'
      path: '/mental-health'
      fullPath: '/mental-health'
      preLoaderRoute: typeof MentalHealthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsul': {
      id: '/konsul'
      path: '/konsul'
      fullPath: '/konsul'
      preLoaderRoute: typeof KonsulRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunitas-pasien': {
      id: '/komunitas-pasien'
      path: '/komunitas-pasien'
      fullPath: '/komunitas-pasien'
      preLoaderRoute: typeof KomunitasPasienRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter': {
      id: '/dokter'
      path: '/dokter'
      fullPath: '/dokter'
      preLoaderRoute: typeof DokterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dermatologi': {
      id: '/dermatologi'
      path: '/dermatologi'
      fullPath: '/dermatologi'
      preLoaderRoute: typeof DermatologiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-dokter': {
      id: '/daftar-dokter'
      path: '/daftar-dokter'
      fullPath: '/daftar-dokter'
      preLoaderRoute: typeof DaftarDokterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-jantung': {
      id: '/cek-jantung'
      path: '/cek-jantung'
      fullPath: '/cek-jantung'
      preLoaderRoute: typeof CekJantungRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/consultations': {
      id: '/doctor/consultations'
      path: '/consultations'
      fullPath: '/doctor/consultations'
      preLoaderRoute: typeof DoctorConsultationsRouteRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/chat': {
      id: '/doctor/chat'
      path: '/chat'
      fullPath: '/doctor/chat'
      preLoaderRoute: typeof DoctorChatRouteRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/live-chat': {
      id: '/admin/live-chat'
      path: '/live-chat'
      fullPath: '/admin/live-chat'
      preLoaderRoute: typeof AdminLiveChatRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDoctorsRouteRoute: typeof AdminDoctorsRouteRoute
  AdminLiveChatRouteRoute: typeof AdminLiveChatRouteRoute
  AdminMarketplaceRouteRoute: typeof AdminMarketplaceRouteRoute
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRoute
  AdminUsersRouteRoute: typeof AdminUsersRouteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDoctorsRouteRoute: AdminDoctorsRouteRoute,
  AdminLiveChatRouteRoute: AdminLiveChatRouteRoute,
  AdminMarketplaceRouteRoute: AdminMarketplaceRouteRoute,
  AdminSettingsRouteRoute: AdminSettingsRouteRoute,
  AdminUsersRouteRoute: AdminUsersRouteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorAnalyticsRouteRoute: typeof DoctorAnalyticsRouteRoute
  DoctorChatRouteRoute: typeof DoctorChatRouteRoute
  DoctorConsultationsRouteRoute: typeof DoctorConsultationsRouteRoute
  DoctorPatientsRouteRoute: typeof DoctorPatientsRouteRoute
  DoctorPrescriptionsRouteRoute: typeof DoctorPrescriptionsRouteRoute
  DoctorSettingsRouteRoute: typeof DoctorSettingsRouteRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorAnalyticsRouteRoute: DoctorAnalyticsRouteRoute,
  DoctorChatRouteRoute: DoctorChatRouteRoute,
  DoctorConsultationsRouteRoute: DoctorConsultationsRouteRoute,
  DoctorPatientsRouteRoute: DoctorPatientsRouteRoute,
  DoctorPrescriptionsRouteRoute: DoctorPrescriptionsRouteRoute,
  DoctorSettingsRouteRoute: DoctorSettingsRouteRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ArtikelRouteRoute: ArtikelRouteRoute,
  AuthRouteRoute: AuthRouteRoute,
  BannedRouteRoute: BannedRouteRoute,
  BerandaRouteRoute: BerandaRouteRoute,
  BookingRouteRoute: BookingRouteRoute,
  CekJantungRouteRoute: CekJantungRouteRoute,
  ChatRouteRoute: ChatRouteRoute,
  DaftarDokterRouteRoute: DaftarDokterRouteRoute,
  DermatologiRouteRoute: DermatologiRouteRoute,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  DokterRouteRoute: DokterRouteRoute,
  KomunitasPasienRouteRoute: KomunitasPasienRouteRoute,
  KonsulRouteRoute: KonsulRouteRoute,
  MaintenanceRouteRoute: MaintenanceRouteRoute,
  MarketplaceRouteRoute: MarketplaceRouteRoute,
  MembershipRouteRoute: MembershipRouteRoute,
  MentalHealthRouteRoute: MentalHealthRouteRoute,
  MoodCheckRouteRoute: MoodCheckRouteRoute,
  PaymentRouteRoute: PaymentRouteRoute,
  ProfilRouteRoute: ProfilRouteRoute,
  RekamMedisRouteRoute: RekamMedisRouteRoute,
  ResepRouteRoute: ResepRouteRoute,
  SymptomTriageRouteRoute: SymptomTriageRouteRoute,
  TwinRouteRoute: TwinRouteRoute,
  VideoEdukasiRouteRoute: VideoEdukasiRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
